spring:
  datasource:
    url: jdbc:mysql://${DEV_MYSQL_HOST}:${DEV_MYSQL_PORT}/ramal
    username: ${DEV_MYSQL_USER}
    password: ${DEV_MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    locations:
      - classpath:db/migration