spring:
  datasource:
    url: jdbc:mysql://${DEV_MYSQL_HOST}:${DEV_MYSQL_PORT}/ramal
    username: ${DEV_MYSQL_USER}
    password: ${DEV_MYSQL_PASSWORD}
#    url: jdbc:mysql://192.168.0.160:3306/ramal
#    username: developer
#    password: salvador1
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    baselineOnMigrate: true
    locations=classpath: db/migration