spring:
  datasource:
    url: jdbc:mysql://${DEV_MYSQL_HOST}:${DEV_MYSQL_PORT}/extension
    username: ${DEV_MYSQL_USER}
    password: ${DEV_MYSQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    baselineOnMigrate: true
    locations=classpath: db/migration