spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/ramal
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
#    url: jdbc:mysql://192.168.0.160:3306/ramal
#    username: root
#    password: salvador1
#    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    locations:
      - classpath:db/migration